services:
  - type: web
    name: f-hms-1
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
