services:
  - type: web
    name: f-hms-1
    env: node
    rootDir: backend
    buildCommand: rm -rf node_modules package-lock.json && npm install
    startCommand: node --experimental-specifier-resolution=node index.js
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
